[project]
name = "rag-api"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "chromadb>=1.4.1",
    "fastapi>=0.128.0",
    "nltk>=3.9.2",
    "ollama>=0.6.1",
    "tiktoken>=0.12.0",
    "uvicorn>=0.40.0",
]
